services:
  postgres:
    # Especifica a imagem Docker que será usada. Estamos usando a imagem oficial do PostgreSQL.
    # Você pode especificar uma versão, como 'postgres:13', ou usar 'latest' para a mais recente.
    image: postgres:latest
    
    # Define um nome para o contêiner para facilitar a identificação.
    container_name: postgres_db
    
    # Configura as variáveis de ambiente necessárias para inicializar o contêiner do PostgreSQL.
    environment:
      POSTGRES_USER: admin      # Define o nome de usuário para o superusuário do banco.
      POSTGRES_PASSWORD: admin  # Define a senha para este usuário. **Mude para uma senha forte em produção.**
      POSTGRES_DB: book_api     # Define o nome do banco de dados que será criado na inicialização.
    
    # Mapeia as portas. A porta 5432 do contêiner será exposta na porta 5432 da sua máquina local.
    # Formato: "PORTA_LOCAL:PORTA_DO_CONTÊINER"
    ports:
      - "5432:5432"
      
    # Define um volume para persistir os dados do banco de dados.
    # Isso garante que seus dados não sejam perdidos se o contêiner for removido e recriado.
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Declaração dos volumes para que o Docker os gerencie.
volumes:
  postgres_data: